### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by PaszaVonPomiot** [Shampra/EvernoteToAnytype#3]
v0.8

Multiple notes exported from Evernote to one file. Tried to convert the file and got following:

```
('C:/Users/xxx/Desktop/EVER_EXPORT/401_500.enex',)
['C:\\Users\\xxx\\Desktop\\EVER_EXPORT\\401_500.enex']
Conversion de 401_500.enex...
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1921, in __call__
  File "customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
  File "main.py", line 69, in convert
  File "converter.py", line 652, in convert_files
  File "converter.py", line 220, in get_files
AttributeError: 'NoneType' object has no attribute 'strip'
```

I strongly recommend you use type annotations and mypy.

**Comment by Shampra** [comment]
You're right ;-).  
I have many things to do to make code more robust.  
Since AT has an issue with importing files and bugs, I've put it on hold for a while...  
  
In progress for type annotations!  
  
Can you give me your Evernote version please?

**Comment by PaszaVonPomiot** [comment]
### Version
10.67.4-win-ddl-public (20231204112355)
Editor: v176.32.0
Service: v1.80.3

**Comment by Shampra** [comment]
Bug found : sometimes Evernote export files without filename.
The patch will be integrated into the 0.8.3

**Comment by Shampra** [comment]
No return, I suppose it's ok (if not, reopen a ticket, thanks)
